name: coar
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.1.0
  scroll_indicator: ^0.0.3
  camera: ^0.11.0+1
  permission_handler: ^11.3.1
  vector_math: ^2.1.0
  image_picker: ^1.0.8
  google_mlkit_face_detection: ^0.11.0
  google_ml_kit: ^0.18.0
  image: ^4.2.0
  dotted_border: ^2.1.0
  webview_flutter: ^2.0.13
  firebase_core: ^3.7.0
  cloud_firestore: ^5.4.5 
  cloud_functions: ^5.0.2
  firebase_auth: ^5.1.1
  firebase_database: ^11.0.2
  firebase_storage: ^12.1.0
  mime: ^1.0.5
  firebase_messaging: ^15.0.2
  flutter_local_notifications: ^17.1.2
  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  firebase_analytics: ^11.1.0
  firebase_crashlytics: ^4.0.2
  get_it: ^7.7.0
  equatable: ^2.0.5
  hive: ^2.2.3
  location: ^6.0.2
  image_cropper: ^5.0.1
  intl: ^0.19.0
  uuid: ^4.4.2
  
dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/cor..jpg"
  min_sdk_android: 21 

flutter:
  assets:
    - asset/
